name: Push SRC to dev branch

on:
  pull_request:
    branches: [dev]

  push:
    branches: [dev]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository code
        uses: actions/checkout@v4  

      - name: Set up python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: "pip"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Lint with black
        run: black src
      
      - name: Lint with flake8
        run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Quality check
        run: pylint src | tee pylint_output.txt

