name: Full python  CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set ip python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Verify python version
        run: |
          echo "Current Working Directory (where the code is): $(pwd)"
          python --version

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run unitests and integration tests
        run: pytest -v tests/

